# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Neuroimaging and Machine Learning for Biomedicine
copyright: "2023-2025" 
author: Nadezhda Alsahanova, Aleksandra Beliaeva, Dmitriy Kornilov, Fedor Gubanov, Pavel Bartenev, Maxim Sharaev
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: NeuroML.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/BIMAI-lab/NEUROML_course  # Online location of your book
  path_to_book: /  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "./logo.png"
  use_issues_button: true
  use_repository_button: true
  extra_css:
   - _static/myadmonitions.css
