name: nml_course_meth
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.10
  - pip=23.3.1
  - pip:
    - numpy==1.26
    - pandas==1.4.4
    - PyWGCNA==1.20.4
    - biomart==0.9.2
    - pyvis==0.3.1
    - matplotlib==3.8.0
    - seaborn==0.13.0
    - scipy==1.8.0
    - nibabel==5.1.0
    - nilearn==0.7.1
    - antspyx==0.3.8
    - h5py==3.1.0
    - mne>=0.23.4
    - xarray>=0.18
    - joblib>=1.0.0
    - mne-connectivity==0.6.0
    - SimpleITK==2.1.1
    - nipype==1.8.6
    - jupyter-book==0.15.1
    - jupyter-server<2.0.0

