name: nml_course
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.10
  - pip=23.3.1
  - r-base=4.2
  - bioconductor-deseq2=1.38
  - bioconductor-degreport=1.34.0
  - bioconductor-summarizedexperiment=1.28.0
  - pip:
    - numpy==1.26
    - pandas==2.1.1
    - scipy==1.11.3
    - scikit-learn==1.3.2
    - matplotlib==3.8.0
    - seaborn==0.13.0
    - nibabel==5.1.0
    - nilearn==0.7.1
    - antspyx==0.3.8
    - h5py==3.1.0
    - SimpleITK==2.1.1
    - nipype==1.8.6
    - mne>=0.23.4
    - xarray>=0.18
    - joblib>=1.0.0
    - mne-connectivity==0.6.0
    - jupyter-book==0.15.1
    - jupyter-server<2.0.0